version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/nk_pr
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A nekidaem worker -l info
    volumes:
      - .:/nk_pr
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A nekidaem beat -l info
    volumes:
      - .:/nk_pr
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
