# Generated by Django 4.0.4 on 2022-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_blog'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='read',
            field=models.ManyToManyField(blank=True, default=None, related_name='readers', to='blog.article', verbose_name='Прочитано'),
        ),
    ]
